### ISSUE TITLE
ಒತ್ತಕ್ಷರ ಸಮಸ್ಯೆ

### ISSUE THREAD

**Issue by kiranlinganur** [kishorechan/Nishchaya#1]
![20220813_091938](https://user-images.githubusercontent.com/30698626/184467448-3b17d89d-a311-4a9a-9e8f-83b8431e37fe.png)

**Comment by kishorechan** [comment]
I am still looking to solution to this problem.  I have already mentioned about this in the Readme.  Will rectify in some time.
https://graphicdesign.stackexchange.com/questions/157966/font-forge-below-base-forms-overlapping

**Comment by shankarsivarajan** [comment]
You probably need to use mark-to-mark anchors. Watch [this](https://www.youtube.com/watch?v=io56-xzCbms) video by Fredrick Brennan on diacritics.

**Comment by kishorechan** [comment]
Thanks a ton @shankarsivarajan This solved my long pending issue.  Will be releasing this in Beta.

**Comment by kishorechan** [comment]
This issue has been fixed now.
