### ISSUE TITLE
Spelling mistake 

### ISSUE THREAD

**Issue by kiranlinganur** [kishorechan/Nishchaya#2]
![20220813_204228](https://user-images.githubusercontent.com/30698626/184500177-a01a0f63-5d56-4df7-b2f8-f3111733b53c.jpg)

**Comment by kishorechan** [comment]
Its not a spelling mistake.  The "Arkavattu" is omitted by design. This has been mentioned in Readme. The Arkavattu is a Sanskrit derivative and has not be added here.
